import javax.swing.*;
public class AdminView extends javax.swing.JFrame {

   public static int open=0;
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Insert = new javax.swing.JButton();
        Btn_Update = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        Btn_ViewQ = new javax.swing.JButton();
        Btn_ViewS = new javax.swing.JButton();
        Btn_Logout = new javax.swing.JButton();
        Btn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_InStud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Insert.setBackground(new java.awt.Color(204, 255, 255));
        Btn_Insert.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_Insert.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Insert.setText("Insert Question");
        Btn_Insert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertActionPerformed(evt);
            }
        });

        Btn_Update.setBackground(new java.awt.Color(204, 255, 255));
        Btn_Update.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_Update.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Update.setText("Update Question");
        Btn_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Delete.setBackground(new java.awt.Color(204, 255, 255));
        Btn_Delete.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_Delete.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Delete.setText("Delete Question");
        Btn_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_ViewQ.setBackground(new java.awt.Color(204, 255, 255));
        Btn_ViewQ.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_ViewQ.setForeground(new java.awt.Color(0, 153, 153));
        Btn_ViewQ.setText("View All Question");
        Btn_ViewQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_ViewQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ViewQActionPerformed(evt);
            }
        });

        Btn_ViewS.setBackground(new java.awt.Color(204, 255, 255));
        Btn_ViewS.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_ViewS.setForeground(new java.awt.Color(0, 153, 153));
        Btn_ViewS.setText("View All Student Result");
        Btn_ViewS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_ViewS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ViewSActionPerformed(evt);
            }
        });

        Btn_Logout.setBackground(new java.awt.Color(204, 255, 255));
        Btn_Logout.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_Logout.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Logout.setText("Logout");
        Btn_Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_LogoutMouseClicked(evt);
            }
        });
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });

        Btn_Exit.setBackground(new java.awt.Color(204, 255, 255));
        Btn_Exit.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_Exit.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Exit.setText("Exit");
        Btn_Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poor Richard", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ADMIN CONTROLS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Btn_InStud.setBackground(new java.awt.Color(204, 255, 255));
        Btn_InStud.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        Btn_InStud.setForeground(new java.awt.Color(0, 153, 153));
        Btn_InStud.setText("ADD Student");
        Btn_InStud.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_InStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InStudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_ViewQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_ViewS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_InStud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Btn_InStud)
                .addGap(18, 18, 18)
                .addComponent(Btn_Insert)
                .addGap(18, 18, 18)
                .addComponent(Btn_Update)
                .addGap(18, 18, 18)
                .addComponent(Btn_Delete)
                .addGap(18, 18, 18)
                .addComponent(Btn_ViewQ)
                .addGap(18, 18, 18)
                .addComponent(Btn_ViewS)
                .addGap(18, 18, 18)
                .addComponent(Btn_Logout)
                .addGap(18, 18, 18)
                .addComponent(Btn_Exit)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        
        
        JOptionPane.showConfirmDialog(null,"Do You Really Want To Logout???","Select",JOptionPane.YES_NO_OPTION);
        
            setVisible(false);
            new LoginForm().setVisible(true);
        
        
    }//GEN-LAST:event_Btn_LogoutActionPerformed

    private void Btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LogoutMouseClicked

    private void Btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExitActionPerformed
        
        
         JOptionPane.showConfirmDialog(null,"Do You Really Want To Logout From Project???","Select",JOptionPane.YES_NO_OPTION);
        
            System.exit(0);
        
        
    }//GEN-LAST:event_Btn_ExitActionPerformed

    private void Btn_InStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InStudActionPerformed
        setVisible(false);
        new StudentRegistration().setVisible(true);
    }//GEN-LAST:event_Btn_InStudActionPerformed

    private void Btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertActionPerformed
        setVisible(false);
        new InsertQuestion().setVisible(true);
    }//GEN-LAST:event_Btn_InsertActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        setVisible(false);
        new UpdateQuestion().setVisible(true);
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        setVisible(false);
        new UpdateQuestion().setVisible(true);
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_ViewQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ViewQActionPerformed
        setVisible(false);
        new ViewALLQuestions().setVisible(true);
    }//GEN-LAST:event_Btn_ViewQActionPerformed

    private void Btn_ViewSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ViewSActionPerformed
        
        setVisible(false);
        new ViewStudentResult().setVisible(true);
    }//GEN-LAST:event_Btn_ViewSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Exit;
    private javax.swing.JButton Btn_InStud;
    private javax.swing.JButton Btn_Insert;
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JButton Btn_ViewQ;
    private javax.swing.JButton Btn_ViewS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
